### ISSUE TITLE
Understand type hints

### ISSUE THREAD

**Issue by sametmax** [KristoforMaynard/SublimeAutoDocstring#11]
If I got:

```
def main(module, stuff: int=1, foo="bar"):
    """Summary

    Args:
        module (TYPE): Description
        stuff (TYPE): Description

    Returns:
        TYPE: Description
    """
```

The console shows that AutoDocString raises a syntax error.

**Comment by KristoforMaynard** [comment]
Indeed, the syntax error comes from the fact that the argument list parser makes an abstract syntax tree using a lambda function instead of a normal function. This made it easier to sort through the ast, but lambda functions do not support annotations. The solution to this is to do away with the lambda function hack [here](https://github.com/KristoforMaynard/SublimeAutoDocstring/blob/master/auto_docstring.py#L489). Then, one can additionally get the type hints out of the ast. Another small snag will be that the regex for function declarations [here](https://github.com/KristoforMaynard/SublimeAutoDocstring/blob/master/auto_docstring.py#L29) will not match if a return type hint is given. This would also need to be fixed.

I won't likely get around to fixing this for some time, so in the mean time anyone should feel free to take a crack at it :)

**Comment by KristoforMaynard** [comment]
As of version 0.4.0, there is preliminary support for type hints. Since Python does not enforce any clear use or syntax for type hints in an annotation, the current implementation is my best guess for how developers might use annotations. Feedback is definitely welcome! :)

**Comment by sametmax** [comment]
Awesome !

From 3.5, type hints follow the standard set by the lib mypy, using the content of the `typing` module for more complex definition.

I tested your solution, and it works for simple types, but not for more complicated types:

```
def bar(self, foo: typing.Union(typing.Callable, typing.Iterable)):
    """Summary

    Returns:
        TYPE: Description


    Args:
        foo (<_ast.Attribute object at 0x7fc6ed854290>): Description
    """
```

You can, however, get a decently human readable representation of foo's type by calling repr() on it. And you can detect it's a type since __module__ is set to "typing".

Also, I noticed changing the type and running the AutoDocstring doesn't update the type. Is it on purpose ?

**Comment by KristoforMaynard** [comment]
Aha! I was unaware of the typing module; I suppose some more googling would have led me there :S.

In principle, I do think I should update types to stay in sync with annotations. My reservation in doing that at the moment is that, as you noticed, I'm using a very naive method to parse the annotations. I expect that users will probably edit the docstring to their liking, and in that case, it would be annoying when updating the docstring if the type constantly changes to something that you don't want. I suppose there could be a setting such that a user could indicate that they would rather keep types up to date no matter what - but I think more than anything, a more robust annotation parser is preferred.
