### ISSUE TITLE
AutoDocString not generated with multi line parameter functions

### ISSUE THREAD

**Issue by edendekker** [KristoforMaynard/SublimeAutoDocstring#42]
# Scenario
Multi line parameter functions. No generation - 
```
def new_process(
    self, instance_number=0, socks5proxy_host=None, socks5proxy_port=1080
):
    pass
```

Single line parameter functions. Successful generation - 
```
def new_process(self, instance_number=0, socks5proxy_host=None, socks5proxy_port=1080):
    """Summary.

    Args:
        instance_number (int, optional): Description
        socks5proxy_host (None, optional): Description
        socks5proxy_port (int, optional): Description

    Returns:
        bool: Description.
    """
    pass
```
# Feature Request
Enable multi line parameter functions for doc string generation.
I use flake8 lint plugin for code styling.  
To prevent the 80 char per line rule from being breached, i use multi line parameters for my functions.

PS. Fantastic Plugin :+1:  :smiley:

**Comment by KristoforMaynard** [comment]
Interesting! This isn't a problem with multiple lines per se. It appears it's an issue with the closing parenthesis being immediately preceeded by a newline. Adding a single space before the closing paren makes it work as expected.

This is probably an issue with the regex at the top of auto_docstring.py:

```
__class_re = r"(class)\s+([^\s\(\):]+)\s*(\(([\s\S]*?)\))?"
__func_re = r"(?:async\s*)?(def)\s+([^\s\(\):]+)\s*\(([\s\S]*?)\)\s*(->.*?)?"

_all_decl_re = r"^[^\S\n]*({0}|{1})\s*:".format(__class_re, __func_re)
_class_decl_re = r"^[^\S\n]*{0}\s*:".format(__class_re)
_func_decl_re = r"^[^\S\n]*{0}\s*:".format(__func_re)
```

As you can see, this regex is rather complicated to support the function annotation syntax. I expect the fix is probably as simple as putting an extra \s in the right place in __func_re (and probably __class_re too?). I'll have a go at it when I get a free moment.

**Comment by loscil06** [comment]
This problem still persists as the newest version. Please take a look at it if possible. Thanks a lot!
